### ISSUE TITLE
Bugged Decoration

### ISSUE THREAD

**Issue by Voidking18** [InusualZ/MHTriServer#2]
Hi I recently got a dragon gem these past couple of days 3 slot with nothing else on it and it just turned into a two slot and erased one of my decoration jkust a vitality but still i have pictures and just thought you should know i can hope for another and grind jho for it but still kinda sucks there goes my health+20

**Comment by Voidking18** [comment]
![Uploading Screenshot (3).png…]()

**Comment by Voidking18** [comment]
![Screenshot (4)](https://github.com/InusualZ/MHTriServer/assets/157366720/574afc88-7882-4756-9fc5-241071146c08)
![Screenshot (5)](https://github.com/InusualZ/MHTriServer/assets/157366720/4a3f5e16-d92e-413a-8714-2b5709c3a9c4)

**Comment by Voidking18** [comment]
it was in inventory untouched and im so disheartend by it this stops my 285 hour character please fix bugs like this

**Comment by InusualZ** [comment]
I’m sorry this happened to you, but the server software has no interaction with items, quest or inventory. The server function as hub. It connect the players together and the game do the rest.

Also, I don’t know if you are aware but there is a public beta that you can participate.

**Comment by Voidking18** [comment]
that was in the public beta

**Comment by Voidking18** [comment]
![Screenshot (3)](https://github.com/InusualZ/MHTriServer/assets/157366720/721de0a5-8cec-498e-adbe-7ce3ce76b233)

**Comment by Voidking18** [comment]
screenshot 3 that never uploaded

**Comment by Voidking18** [comment]
and you're open beta discord still thinks im hacking you ruined my save
